metadata.format.version = "1.1"

[versions]
fabric-loader = "2.0.0+fabric.0.17.2"

paper-api = "1.21.6-R0.1-SNAPSHOT"
nbtapi = "2.12.4"

gradle-spotless = "6.25.0"
gradle-paperweight = "2.0.0-build.5+2.0.0-beta.18"
gradle-shadow = "9.1.0"

[libraries]
fabric-loader = { module = "com.floweytf.fabricpaperloader:fabric-paper-loader", version.ref = "fabric-loader" }

paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper-api" }
nbtapi = { module = "de.tr7zw:item-nbt-api", version.ref = "nbtapi" }
nbtapi-plugin = { module = "de.tr7zw:item-nbt-api-plugin", version.ref = "nbtapi" }

gradle-spotless = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "gradle-spotless" }
gradle-paperweight = { module = "com.playmonumenta.paperweight-aw:paperweight-userdev", version.ref = "gradle-paperweight" }
gradle-shadow = { module = "com.gradleup.shadow:shadow-gradle-plugin", version.ref = "gradle-shadow" }

[bundles]
gradle = ["gradle-paperweight", "gradle-shadow", "gradle-spotless"]
